openapi: 3.0.1
info:
  title: DataServiceSample_API
  description: API Definition of DataServiceSample_API
  version: 1.0.0
servers:
- url: http://localhost:8290/service
paths:
  /add:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /update:
    put:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /delete:
    delete:
      responses:
        default:
          description: Default response
  /getdata:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
